services:
  - type: web
    name: scraper
    env: python
    buildCommand: |
      apt-get update
      apt-get install -y wget unzip google-chrome-stable chromium-chromedriver
      pip install -r requirements.txt
    startCommand: ./start.sh
    envVars:
      - key: GOOGLE_CHROME_BIN
        value: /usr/bin/google-chrome
      - key: CHROMEDRIVER_PATH
        value: /usr/bin/chromedriver
